version: '2.1'

services:
  
  knx-control:
    build: .
    restart: always
    network_mode: host
    healthcheck:
      test: "node node_modules/healthcheck.js"
      interval: 5s
      timeout: 5s
      retries: 20
    restart: always
    volumes:
      - /home/docker/knx-control:/home/node/app
    depends_on:
      knxd:
        condition: service_healthy
      homebridge-knx:
        condition: service_healthy
    command: ["npm", "start"]
        
  homebridge-knx:
    image: spanghf37/homebridge-knx:amd64
    restart: always
    network_mode: host
    healthcheck:
      test: "curl -f http://localhost:18081"
      interval: 5s
      timeout: 5s
      retries: 20
    restart: always
    volumes:
      - /home/docker/knx-control/config:/root/.homebridge/
    depends_on:
      knxd:
        condition: service_healthy
  knxd:
    image: spanghf37/knxd:amd64
    restart: always
    volumes:
      - /home/docker/knx-control/config:/etc/knxd/
    network_mode: host
    #links:
      #- db
    healthcheck:
      test: "/home/docker-healthcheck"
      interval: 5s
      retries: 10

volumes:
  knx-control:
  homebridge:
  knxd:
