version: "2"
services:
  #db:
  #  image: amd64/mysql:latest
    #environment:
      #MYSQL_ROOT_PASSWORD: myrootpassword
  #  volumes:
  #    - ./knx-db-data:/var/lib/mysql
  #  env_file:
  #    - 'default.docker-env'
  #  ports:
  #    - 3306:3306
  #  expose:
  #    - "3306"
  node:
    build: .
    #working_dir: /home/node/app
    # environment:
    #  - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    env_file:
      - 'default.docker-env'
    #depends_on:
    #  - db
    command: ["npm", "start"]
